# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c73748eb0a96c3e673de7ca26da8c74b429f1b46585a07c4652b03fb31d0cb2d3f53938c3280ad2bc0c2cf23470467883e8d169edfc3f294494c42ff5e65fa3

test:
  secret_key_base: 5472d0349af5a73bc9a7bbffd6f0e78d726dadddc25d70435a79c04152bf8edc9d7180b114f65c1e771cc46686fb177f230e9c88218abbfc30abc6903e0edec9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
